services:
  mysql-server:
    env_file:
      - .env
    container_name: mysql-server
    hostname: mysql-server
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql-server:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo